### ISSUE TITLE
Page not loading after adding filters

### ISSUE THREAD

**Issue by Gonzalo933** [vivekratnavel/omniboard#63] opened 2019-02-08 11:38 UTC
This issue is really hard to reproduce as it seems to happen randomly to me.

Sometimes when I add some filters and reload the webpage it shows for a second and then goes white. There is no error in the console and the only way to fix it is deleting the cookies/stored data from my browser.

This is the output of the console (with the request decoded to be legible):

> ::ffff:127.0.0.1 - - [08/Feb/2019:11:34:37 +0000] "GET /api/v1/Runs?select=_id,heartbeat,experiment,command,artifacts,host,stop_time,config,result,start_time,resources,format,status,omniboard,metrics,meta&sort=-_id&query={"$and":[{"$or":[{"status":{"$eq":"COMPLETED"}},{"status":{"$eq":"FAILED"}},{"status":{"$eq":"INTERRUPTED"}},{"status":{"$eq":"TIMEOUT"}},{"$and":[{"status":"RUNNING"},{"heartbeat":"<1549625556922"}]},{"status":{"$eq":"QUEUED"}}]},{"config.dataset.name":{"$eq":"Australian"}},{"config.model.name":{"$eq":"dgp_aepmcm"}},{"config.model.num_layers":{"$eq":2}}]}&populate=metrics HTTP/1.1" 200 134664 278.835 ms

**Comment by vivekratnavel** [comment] 2019-02-08 19:38
@Gonzalo933 I think it is because you have selected `COMPLETED, FAILED, INTERRUPTED, TIMEOUT` statuses from `Status` filter and have `status: RUNNING` selected in the advanced filter. You have to either remove `RUNNING` from advanced filter or add `RUNNING` to the status filter to see valid results. You see a blank page because the above query will return zero rows.

**Comment by Gonzalo933** [comment] 2019-02-08 20:32
That may be the problem (but I don't remember changing the status filter), the thing is that is not possible to change the filters anymore as just a blank page is shown (full white, no headers, no empty tables, nothing)

**Comment by vivekratnavel** [comment] 2019-02-08 21:02
I see. I will try to reproduce this issue and update you. Until then, you can clear application storage in the browser manually or open a new incognito window. Cheers!

**Comment by vivekratnavel** [comment] 2019-03-09 09:02
I am not able to reproduce this error. Reopen this if it can be reproduced.

**Comment by Gonzalo933** [comment] 2019-03-26 12:11
Well I still have the bug and found out that there is a traceback in my browser console (it's kind of obscured though):

`TypeError: "t.getObjectAt(...) is undefined"
	value http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:946890
	Cn http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:457752
	Dn http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:463362
	n http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:472111
	Xn http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:472419
	fr http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:475803
	lr http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:475312
	sr http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:475138
	ir http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:474510
	Qn http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:473869
	enqueueSetState http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:506057
	setState http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:404555
	loadData http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:662927
	exports http://127.0.0.1:9000/static/js/main.6b74bbb1.js:1:685495
`

**Comment by vnmabus** [comment] 2019-03-26 15:35
This also happens to me if I use Firefox. I am using Omniboard on Chrome to prevent that.

**Comment by vivekratnavel** [comment] 2019-03-27 00:11
@Gonzalo933 @vnmabus Can you post the server log and network console in Chrome when this happens?

**Comment by vivekratnavel** [comment] 2019-03-31 04:38
I tried to reproduce this error in Firefox, but unable to. 

@Gonzalo933 Can you give the exact steps to reproduce this issue?

**Comment by Gonzalo933** [comment] 2019-04-02 10:34
I have tried but it's not possible to find steps to reproduce it. It seems to happen randomly when messing with filters. I will keep trying

**Comment by vivekratnavel** [comment] 2019-04-03 00:18
Thanks @Gonzalo933! Also, please capture the last request and response in network tab, and console tab. That will help a lot with debugging.

**Comment by vivekratnavel** [comment] 2019-09-03 06:58
Closing this now since I believe this will not happen in versions >=2.0.0

Feel free to reopen if you are facing the same issue.

**Closed by vivekratnavel** 2019-09-03 06:58 UTC
