### ISSUE TITLE
Compare metrics view bug

### ISSUE THREAD

**Issue by MaxSchambach** [vivekratnavel/omniboard#218] opened 2020-06-05 10:03 UTC
# Description
I have noticed a small bug in the Compare Metrics view. Since #180 it is possible to use the ExperimentName as the legend label. #216 extended this to arbitrary config values.
However, when e.g. plotting two different experiments with the same ExperimentName, only one will actually be plotted and it will incorrectly show that the other experiment has the same values.
This does not happen, when using the _id or legend labels that are not equal.

I.e., when the labels of multiple plots are identical, the plots are not shown as separate plots but are identical. I assume, that the legend label is somehow used to distinguish the plots in Plotly? I don't know if there is anything on the Omniboard side to do except always include the unique _id in the label to make all legend labels distinct or somehow set a distinct value in the background regardless of the legend label?

**Comment by vivekratnavel** [comment] 2021-07-11 08:17
Hi @MaxSchambach,

This is a good point. To work around this issue, there is an option to add multiple values to the label to make the label unique.

<img width="1176" alt="Screen Shot 2021-07-11 at 1 14 33 AM" src="https://user-images.githubusercontent.com/1051198/125187663-8e887500-e1e5-11eb-939c-c06056bbcfaa.png">

As it can be seen in the screenshot, if you want to use the experiment name as the label, you should also add an id to the label to make it unique. You can do this by clicking on the "+" button.

**Comment by vivekratnavel** [comment] 2021-07-11 19:55
I am inclined to close this issue since it is not a bug. It is the user's responsibility to make the label unique by adding a combination of label values.

**Closed by vivekratnavel** 2021-07-11 19:55 UTC
