### ISSUE TITLE
trying to download source files causes error

### ISSUE THREAD

**Issue by tfriedel** [vivekratnavel/omniboard#169] opened 2019-11-30 10:30 UTC
I'm using the docker image for 2.4.3.
When clicking the download box for a source file, omniboard crashes with this error:
```
An error occurred:  { MongoError: file with id training not opened for writing
    at Function.create (/usr/omniboard/node_modules/mongodb/lib/core/error.js:44:12)
    at /usr/omniboard/node_modules/mongodb/lib/gridfs/grid_store.js:948:22
    at result (/usr/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at session.endSession (/usr/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:64:11)
    at ClientSession.endSession (/usr/omniboard/node_modules/mongodb/lib/core/sessions.js:135:41)
    at executeCallback (/usr/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:59:17)
    at handleCallback (/usr/omniboard/node_modules/mongodb/lib/utils.js:129:55)
    at cursor.next (/usr/omniboard/node_modules/mongodb/lib/operations/find_one.js:28:7)
    at result (/usr/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at executeCallback (/usr/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/usr/omniboard/node_modules/mongodb/lib/utils.js:129:55)
    at cursor._next (/usr/omniboard/node_modules/mongodb/lib/operations/common_functions.js:238:5)
    at self._initializeCursor (/usr/omniboard/node_modules/mongodb/lib/core/cursor.js:750:9)
    at handleCallback (/usr/omniboard/node_modules/mongodb/lib/core/cursor.js:32:5)
    at _setCursorNotifiedImpl (/usr/omniboard/node_modules/mongodb/lib/core/cursor.js:694:38)
    at self._endSession (/usr/omniboard/node_modules/mongodb/lib/core/cursor.js:703:39)
  driver: true,
  name: 'MongoError',
  [Symbol(mongoErrorContextSymbol)]: {} }
/usr/omniboard/node_modules/mongodb/lib/utils.js:133
      throw err;
      ^

MongoError: file with id training not opened for writing
    at Function.create (/usr/omniboard/node_modules/mongodb/lib/core/error.js:44:12)
    at /usr/omniboard/node_modules/mongodb/lib/gridfs/grid_store.js:948:22
    at result (/usr/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at session.endSession (/usr/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:64:11)
    at ClientSession.endSession (/usr/omniboard/node_modules/mongodb/lib/core/sessions.js:135:41)
    at executeCallback (/usr/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:59:17)
    at handleCallback (/usr/omniboard/node_modules/mongodb/lib/utils.js:129:55)
    at cursor.next (/usr/omniboard/node_modules/mongodb/lib/operations/find_one.js:28:7)
    at result (/usr/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:75:17)
    at executeCallback (/usr/omniboard/node_modules/mongodb/lib/operations/execute_operation.js:68:9)
    at handleCallback (/usr/omniboard/node_modules/mongodb/lib/utils.js:129:55)
    at cursor._next (/usr/omniboard/node_modules/mongodb/lib/operations/common_functions.js:238:5)
    at self._initializeCursor (/usr/omniboard/node_modules/mongodb/lib/core/cursor.js:750:9)
    at handleCallback (/usr/omniboard/node_modules/mongodb/lib/core/cursor.js:32:5)
    at _setCursorNotifiedImpl (/usr/omniboard/node_modules/mongodb/lib/core/cursor.js:694:38)
    at self._endSession (/usr/omniboard/node_modules/mongodb/lib/core/cursor.js:703:39)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by vivekratnavel** [comment] 2019-12-03 09:51
Duplicate of #153

**Closed by vivekratnavel** 2019-12-03 09:51 UTC
